name: a simple github workflow

on: 
  workflow_dispatch:

jobs:
  a_simple_github_workflow_job:
    name: a simple job
    runs-on: ubuntu-latest
    steps:
      - name: step1
        id: stepId
        run: echo "This is the first iam running a github workflow job"
      - name: step2
        id: shellStep
        shell: python
        run: print("This is the first time iam running a python shell in a github workflow job")
        
